# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: base_link_link_1
  pid: {p: 2000.0, i: 100, d: 500.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_1_link_2
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_2_link_3
  pid: {p: 20000.0, i: 50, d: 1000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_3_link_4
  pid: {p: 2000.0, i: 50, d: 200.0}
# joint5_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: link_4_link_5
#   pid: {p: 700.0, i: 50, d: 70.0} 
joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_5_link_6
  pid: {p: 700.0, i: 50, d: 70.0}   
# joint7_position_controller:
#   type: effort_controllers/JointPositionController
#   joints: 
#     - link_6_link_7
#     - link_6_link_8
#   gains:
#     link_6_link_7 : {p: 700.0, i: 50, d: 70.0}   
#     link_6_link_8 : {p: 700.0, i: 50, d: 70.0}  
joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_6_link_7
  pid: {p: 700.0, i: 50, d: 70.0}
joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: link_6_link_8
  pid: {p: 700.0, i: 50, d: 70.0}  